name: github pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cargo-bins/cargo-binstall@main

      - name: Binstall dioxus-cli
        run: cargo binstall --no-confirm dioxus-cli

      - name: Build web app
        run:  |
          cd web
          dx bundle --out-dir docs

      - name: Deploy to GitHub Pages
        uses: DioxusLabs/deploy-action@0.1.2
        with:
          public-dir: web/docs
