[package]
name = "web"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true

[dependencies]
dioxus = { workspace = true, features = [] }
ui = { workspace = true }

[features]
default = ["web"]
web = ["dioxus/web"]
